#!/bin/sh

# Service Management Logic

# Search paths for systemd units
SYSTEMD_SEARCH_PATHS="$ROOT_DIR/systemd-units /etc/systemd/system /lib/systemd/system /usr/lib/systemd/system"

find_unit_file() {
    local name="$1"
    # Append .service if missing
    case "$name" in
        *.service) ;;
        *) name="${name}.service" ;;
    esac

    for path in $SYSTEMD_SEARCH_PATHS; do
        if [ -f "$path/$name" ]; then
            echo "$path/$name"
            return 0
        fi
    done
    return 1
}

create_pkg() {
    local name="$1"
    local unit_file=$(find_unit_file "$name")
    
    if [ -z "$unit_file" ]; then
        log_error "Unit file for '$name' not found in search paths."
        return 1
    fi

    local repo_dir="${SV_REPO}/${name%.service}"
    
    log_info "Initializing Runit script from $unit_file..."
    $MKDIR_CMD "$repo_dir"
    
    # Extract key fields
    local exec_start=$(parse_ini "$unit_file" "Service" "ExecStart")
    local type=$(parse_ini "$unit_file" "Service" "Type")
    local pid_file=$(parse_ini "$unit_file" "Service" "PIDFile")
    local runtime_dir=$(parse_ini "$unit_file" "Service" "RuntimeDirectory")

    # Generate run script
    local run_script="$repo_dir/run"
    cat <<EOF > "$run_script"
#!/bin/sh
exec 2>&1
# Generated by fake_systemd from $unit_file
# Original Type: ${type:-simple}
#
# [IMPORTANT NOTICE]
# Runit requires services to run in the FOREGROUND.
# Systemd services often default to background (forking) mode.
#
# PLEASE REVIEW THE COMMAND BELOW:
# 1. Remove daemonizing flags (e.g., -d, --daemon, -f)
# 2. Add foreground flags if needed:
#    - sshd: add -D
#    - nginx: add -g 'daemon off;'
#    - dbus-daemon: add --nofork
#

# Ensure Runtime Directories exist
$(
    if [ -n "$runtime_dir" ]; then
        for dir in $runtime_dir; do
            case "$dir" in
                /*) echo "mkdir -p \"$dir\"" ;;
                *)  echo "mkdir -p \"/run/$dir\"" ;;
            esac
        done
    fi
)

# Start service
exec $exec_start
EOF

    chmod +x "$run_script"
    log_info "Generated run script at $run_script"
    
    # Strong Warning
    echo "----------------------------------------------------------------"
    log_warn "SEMI-AUTOMATIC CONVERSION COMPLETE"
    log_warn "Runit script generated at: $run_script"
    echo ""
    log_warn "YOU MUST REVIEW AND EDIT THIS SCRIPT BEFORE STARTING!"
    log_warn "Systemd services often fork to background, which BREAKS Runit."
    log_warn "1. Open the file: vi $run_script"
    log_warn "2. Ensure the command runs in FOREGROUND (e.g., sshd -D, nginx -g 'daemon off;')"
    echo "----------------------------------------------------------------"
}

enable_service() {
    local name="$1"
    local service_name="${name%.service}"
    local repo_dir="${SV_REPO}/${service_name}"
    local active_link="${SV_ACTIVE}/${service_name}"
    local run_script="${repo_dir}/run"

    if [ ! -d "$repo_dir" ]; then
        create_pkg "$name" || return 1
    fi

    if [ -L "$active_link" ] || [ -d "$active_link" ]; then
        log_info "Service $service_name is already enabled."
    else
        $LN_CMD "$repo_dir" "$active_link"
        log_info "Enabled service $service_name."
        
        # Reminder on enable
        echo "----------------------------------------------------------------"
        log_warn "Service enabled. PLEASE VERIFY RUN SCRIPT:"
        echo "   $run_script"
        log_warn "Make sure it runs in the FOREGROUND, or it will restart loop."
        echo "----------------------------------------------------------------"
    fi
}

disable_service() {
    local name="$1"
    local service_name="${name%.service}"
    local active_link="${SV_ACTIVE}/${service_name}"
    
    if [ -L "$active_link" ] || [ -d "$active_link" ]; then
        log_info "Disabling service $service_name..."
        $RM_CMD "$active_link"
    else
        log_warn "Service $service_name is not enabled."
    fi
}

service_control() {
    local action="$1"
    local name="$2"
    local service_name="${name%.service}"
    local service_path="${SV_ACTIVE}/${service_name}"

    if [ ! -d "$service_path" ]; then
        log_error "Service $service_name not found or not enabled."
        return 1
    fi

    case "$action" in
        start)   
            $SV_CMD up "$service_path" 
            ;;
        stop)    $SV_CMD down "$service_path" ;;
        restart) $SV_CMD restart "$service_path" ;;
        status)  $SV_CMD status "$service_path" ;;
        reload)  $SV_CMD hup "$service_path" ;;
        *)       log_error "Unknown action: $action" ;;
    esac
}

is_active() {
    local name="$1"
    local service_name="${name%.service}"
    local service_path="${SV_ACTIVE}/${service_name}"
    
    if [ -d "$service_path" ]; then
        if $SV_CMD check "$service_path" >/dev/null 2>&1; then
            echo "active"
            return 0
        else
            echo "inactive"
            return 3
        fi
    else
        echo "inactive"
        return 4
    fi
}

is_enabled() {
    local name="$1"
    local service_name="${name%.service}"
    local active_link="${SV_ACTIVE}/${service_name}"
    
    if [ -L "$active_link" ] || [ -d "$active_link" ]; then
        echo "enabled"
        return 0
    else
        echo "disabled"
        return 1
    fi
}
